package com.my.bean;

// Generated 2014-2-17 20:09:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * InfoUnit generated by hbm2java
 */
public class InfoUnit implements java.io.Serializable {

	private Integer unitId;
	private String name;
	private Integer scale;
	private String industry;
	private String introduction;
	private Set infoPeriodicals = new HashSet(0);

	public InfoUnit() {
	}

	public InfoUnit(String name, Integer scale, String industry,
			String introduction, Set infoPeriodicals) {
		this.name = name;
		this.scale = scale;
		this.industry = industry;
		this.introduction = introduction;
		this.infoPeriodicals = infoPeriodicals;
	}

	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Set getInfoPeriodicals() {
		return this.infoPeriodicals;
	}

	public void setInfoPeriodicals(Set infoPeriodicals) {
		this.infoPeriodicals = infoPeriodicals;
	}

}
