package com.my.bean;

// Generated 2014-2-17 20:09:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * InfoAuthor generated by hbm2java
 */
public class InfoAuthor implements java.io.Serializable {

	private Integer authorId;
	private String name;
	private Integer age;
	private String idcard;
	private String school;
	private String specialty;
	private String educational;
	private String introduction;
	private Set infoThesises = new HashSet(0);

	public InfoAuthor() {
	}

	public InfoAuthor(String name, Integer age, String idcard, String school,
			String specialty, String educational, String introduction,
			Set infoThesises) {
		this.name = name;
		this.age = age;
		this.idcard = idcard;
		this.school = school;
		this.specialty = specialty;
		this.educational = educational;
		this.introduction = introduction;
		this.infoThesises = infoThesises;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public String getEducational() {
		return this.educational;
	}

	public void setEducational(String educational) {
		this.educational = educational;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Set getInfoThesises() {
		return this.infoThesises;
	}

	public void setInfoThesises(Set infoThesises) {
		this.infoThesises = infoThesises;
	}

}
