package com.my.bean;

// Generated 2014-2-17 20:09:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * InfoAdmin generated by hbm2java
 */
public class InfoAdmin implements java.io.Serializable {

	private Integer adminId;
	private String name;
	private String pass;
	private String rname;
	private String nname;
	private Set infoComments = new HashSet(0);

	public InfoAdmin() {
	}

	public InfoAdmin(String name, String pass, String rname, String nname,
			Set infoComments) {
		this.name = name;
		this.pass = pass;
		this.rname = rname;
		this.nname = nname;
		this.infoComments = infoComments;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getNname() {
		return this.nname;
	}

	public void setNname(String nname) {
		this.nname = nname;
	}

	public Set getInfoComments() {
		return this.infoComments;
	}

	public void setInfoComments(Set infoComments) {
		this.infoComments = infoComments;
	}

}
