package com.my.bean;

// Generated 2014-2-17 20:09:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InfoComment generated by hbm2java
 */
public class InfoComment implements java.io.Serializable {

	private Integer commentId;
	private InfoPeriodical infoPeriodical;
	private InfoUser infoUser;
	private InfoAdmin infoAdmin;
	private InfoThesis infoThesis;
	private String info;
	private Date date;

	public InfoComment() {
	}

	public InfoComment(InfoPeriodical infoPeriodical, InfoUser infoUser,
			InfoAdmin infoAdmin, InfoThesis infoThesis, String info, Date date) {
		this.infoPeriodical = infoPeriodical;
		this.infoUser = infoUser;
		this.infoAdmin = infoAdmin;
		this.infoThesis = infoThesis;
		this.info = info;
		this.date = date;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public InfoPeriodical getInfoPeriodical() {
		return this.infoPeriodical;
	}

	public void setInfoPeriodical(InfoPeriodical infoPeriodical) {
		this.infoPeriodical = infoPeriodical;
	}

	public InfoUser getInfoUser() {
		return this.infoUser;
	}

	public void setInfoUser(InfoUser infoUser) {
		this.infoUser = infoUser;
	}

	public InfoAdmin getInfoAdmin() {
		return this.infoAdmin;
	}

	public void setInfoAdmin(InfoAdmin infoAdmin) {
		this.infoAdmin = infoAdmin;
	}

	public InfoThesis getInfoThesis() {
		return this.infoThesis;
	}

	public void setInfoThesis(InfoThesis infoThesis) {
		this.infoThesis = infoThesis;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
